### ISSUE TITLE
Chomp lines before matching

### ISSUE THREAD

**Issue by petdance** [beyondgrep/ack3#102]
You can do this and match every line: `ack '\s$'`.  This is because there's a `\n` that matches that whitespace.  No reasonable person wants that.

**Comment by n1vux** [comment]
> "No reasonable person wants that"

indeed.

*If* _hypothetically_ there were a memorable workaround, then and only then might a vaguely consistent performance-above-correctness person hypothetically be able to claim "premature chomping is premature optimization". But alas for that line of "reasoning", the simplest expr i can find to cause Ack-as-is to select only lines with terminal superfluous whitespace (other than the `\n`, just before the `\n`, before it's chomped) _and_ match again to highlight the surperfluous spaces (after chomp) it is 

```bash
ack  '\s+(?<!\n)(?=\n|\Z|\z)' # works but overly  complex
ack  '\s+(?<!\n)(?=\Z|\z)' # ok
ack  '\s+(?<!\n)(?=\n|\Z)' # ok 
ack  '\s+(?<!\n)(?=\n|\z)' # ok and SWYM
ack  '\s+(?<!\n)(?=\Z)'   # simplified but mystified 
```
(and even that is fooled by `\r\n` since we chomp both between match and re-match for highlighting -- even on a '\n'=='^J' platform) 

Much as I like lookahead and lookbehind, that doesn't trip off even my fingertips first try.  
And using both on the same token is just weird -- but necessary to prevent \s+ matching the expected terminal \n while anchoring at the right margin whether \n or not.

**Comment by n1vux** [comment]
[pedantic aside]
The only more-performant less-broke half-fix alternative I see is to *never* `chomp`, 
but rely on the original line ending for normal prints 
(unless using `--output` or `-l` or `-c` etc ...)

but 
that will still match `ack '\s+$'` on every line 
and seemingly highlight nothing (or worse break?) on most lines, 
and even if it correctly highlights the right ones properly, 
you only see them if `--pager='less -R'`
or are very lucky that last $SCREEN lines includes a visible highlight and not just false positives
 
*so still doesn't DWIM.*

rejectable alternative !!

**Comment by petdance** [comment]
Now we all chomp: 5659ec9

Double check that there is nothing else in Bill's notes before I close this.
