### ISSUE TITLE
Consider: Should we get rid of ack's autodetection of filter mode?

### ISSUE THREAD

**Issue by petdance** [beyondgrep/ack3#132]
We have an endless number of problems with the confusion about using ack as a filter vs. specifying files vs. letting it find them.  Maybe we could cut the confusion by getting rid of ack's guessing at filter mode and make the user explicitly `ack -`.  ack as a filter is certainly the least-used way of using it.

See https://github.com/beyondgrep/ack2/issues/659 for the latest.

**Comment by stephenostermiller** [comment]
I think the logic should be:

 - has the `--filter` argument, read STDIN
 - detects TTY, don't read STDIN
 - has file arguments, don't read STDIN
 - has the `--nofilter` argument, don't read STDIN
 - otherwise read stdin

The only change to the current behavior would be preferring file arguments over STDIN.

The only thing that would change would be cases like

    echo hello | ack hello hello.txt

which would have previously filtered STDIN and ignored `hello.txt`.   The new behavior would ignore STDIN and filter `hello.txt`.

The change would allow `ack` to be used intuitively with file arguments in contexts that don't have a TTY such as cron jobs or ssh command lines.

The only other case I've seen asked for is allowing **both** STDIN and files to be read.   That could be supported by using both `--filter` and file arguments.

**Comment by petdance** [comment]
ack has been around for over a decade.  Please rest assured that this is not the first time the problems with filtering has come up, or that we've discussed the possible behaviors.  

What you have described is pretty much how ack works now, except for all the problems that we have with TTY detection, like when you're SSHing to another machine, which is what you discovered today.  We have always had problems with TTY detection in various cases.  That's why `--filter` got added to make it explicit.
