### ISSUE TITLE
Adopt a Code of Conduct

### ISSUE THREAD

**Issue by petdance** [beyondgrep/ack3#154]
ack needs a CoC.  It will be also be adopted by ack2 if/when ack2 makes another release.

Should I adopt an existing one?  Write my own? I haven't explored the options.  I welcome comments from the public.

If you've gone through this process before, I'm especially interested in what you chose for a CoC, and why.

**Comment by petdance** [comment]
Option: Contributor Covenant

https://www.contributor-covenant.org/

**Comment by kyzn** [comment]
Here's a few alternatives I've collected [a couple weeks ago](https://github.com/kyzn/Dist-Zilla-Plugin-ContributorCovenant/issues/3).

  - [ ]  [Geek Feminism](http://geekfeminism.wikia.com/wiki/Community_anti-harassment/Policy) (Public License)
  - [ ]  [Citizen Code of Conduct](http://citizencodeofconduct.org/) (CC BY-SA 3.0)
  - [ ]  [Technology Transformation Service](https://github.com/18F/code-of-conduct/blob/master/code-of-conduct.md) (CC0 1.0 Universal)
  - [ ] [perlpolicy](https://metacpan.org/pod/perlpolicy#STANDARDS-OF-CONDUCT) (Artistic License or GNU GPL)
    - [ ] [Dancer](https://metacpan.org/pod/distribution/Dancer2/lib/Dancer2/Policy.pod#STANDARDS-OF-CONDUCT) (same terms as the Perl 5)
  - [ ] [Mojolicious](https://metacpan.org/pod/distribution/Mojolicious/lib/Mojolicious/Guides/Contributing.pod#CODE-OF-CONDUCT) (Artistic License 2.0)
  - [ ] [Django](https://www.djangoproject.com/conduct/) (CC BY 3.0)
  - [ ] [The Perl Conference](https://perlconference.us/tpc-2018-slc/standards-of-conduct/) (CC BY-SA 3.0)

**Comment by petdance** [comment]
I foresee needing to do zero enforcement on it.

**Comment by petdance** [comment]
DevTogether.co uses http://stumptownsyndicate.org/code-of-conduct/

**Comment by n1vux** [comment]
> I foresee needing to do zero enforcement on it.

That statement could be misinterpreted badly ...  
i presume it's contradicting the "if you foresee a lot ... delegate" clause in (3) rather than the "commit to" clause, and the parallel use of "foresee" witnesses to that, but it could be interpreted differently.
Both clauses of (3) are true in general, one does have to commit to it and have adequate mechanism.

How much mechanism is adequate for a sleepy little community is a separate question. 
Yes, the hope is that if we don't admit a*****s to the community to begin with, and if post the CoC at the door they might be dissuaded from visiting, we likely won't need to invoke it often.

Sage Sharp has an interesting commentary on the downside to Copy'n'Paste CoC's and the needs for customized  Reporting Guidelines, and Anonymity yet Transparency on top of the Contributor Covenant. https://otter.technology/blog/2018/09/20/linux-kernel-hastily-adopts-standard-code-of-conduct/
(Boils down to if it doesn't seem like it is workable enforcement framework, why would anyone trust it to work? Anonymity in mechanism, provision to avoid conflict of interest, and transparency seem to be keys to trust. )

(Stumpytown's reporting guidelines includes an external doc by reference. Adding side-files to standard CC CoC would be a good way to extend while retaining recognizable standard? )

What would a rational reporting guideline be for a small community with no management structure aside from a BDL? 
Send to Andy, unless complaining about Andy then send to Rob & Bill ? 
More generally, post to list if not desiring confidentiality/anonymity (e.g. calling out bad behavior on list), and send to most senior dev(s) not implicated otherwise? 

Sage's point that internal discussions of reports in confidence should be on a non-archived medium is well taken. 

FWIW, If our Slack is a Free slack, its History will expire eventually, iirc 10k message roll-off, but if paid, history is visible to new members forever (except if one archives and flushes a private channel when adding members). 
Slack has restrictions on exporting DM logs (all must consent, which may be impossible to achieve if anyone has left!), so Slack N-Way DM is better for confidentiality than Slack Private channels.

**Comment by shlomif** [comment]
Hi all!

Some people voiced some criticism against the CoC adopted by the Linux kernel here - https://www.reddit.com/r/linux/comments/9ghrrj/linuxs_new_coc_is_a_piece_of_shit/ , and they seem to be of merit. There is also a need for a due process of handling complaints.

**Comment by n1vux** [comment]
> There is also a need for a due process of handling complaints.

Basically, one needs both a CoC (which gives a warranty that community members know what not to do and won't do it) and a Reporting Guidelines (which gives advise on how one complains to whom about whom-else, and provided expectation on process). 

One can make analogy to the `LICENSE` : COC ::   `CONTRIBUTING` : Reporting Guidelins  one is the Thou Shalt/ShaltNot/May and the other is the How-To. 

I would really like to see an example of a good RG for a small (very low bus-factor) project without a Foundation or BoD that has a single person as BDL, lead developer, and Community Manager.  In the other project I'm worrying about this for, the BDL/Lead is not the sole CM so an RG that says drop a dime on him to me or on me to him will work. Does having a believable RG require a BDL to name a CM/Regent?

**Comment by n1vux** [comment]
While the natural thing for a Perl based project to adopt would be the **Perl Policy CoC** referenced in list early in the comments, that is quite specific for Modules included in Perl Core. It is not subject to inclusion by reference; "adopting" it would alas violate Listrophy's good suggestion of **"don't roll our own"**. 

(It also embeds the CoC in a larger Policy document and interweaves the RG with the CoC.)

**Comment by petdance** [comment]
Done at b360c8a8
