### ISSUE TITLE
On Windows, patterns with $ will not match

### ISSUE THREAD

**Issue by petdance** [beyondgrep/ack3#229]
This is a revsiting of https://github.com/beyondgrep/ack2/issues/491

This acking

    ack x$

will not find an `x` at the end of a line in Windows, unless the file is over 10M.

The reason is that we have an optimization where we `sysread()` 10M of the file to see if the pattern matches anywhere in that buffer.  On Windows, all the line endings come in as `\r\n` in the `sysread` buffer, so `/x$/` won't match correctly against `x\r\n` in our scanning.

Either we need to not do this optimization on Windows, or we need to `s/\r\n/\n/g` our buffer on Windows before scanning.

**Comment by n1vux** [comment]
Don't toss the optimization.

Windows files arrive via ?FTP and as attachments without being properly marked as "network encoded" (to be decoded on arrival) all the time these days, and we should DWIM with them.

When not if we find a Windows text file on Linux or MaxOSX/BSD, we probably should 
```s/\r\n/\n/g if / \r\n /x;```
everywhere so that the optimization works with `/$/` on those, too. 

Kind of hate to scan the whole of each 10M block an extra time, could probably match for the first `\n` and see if it's a `/\r\n/` or a `/[^\r]\n/` , which could be done with 
```my ($isWin, $aintWin) = $buf =~ m{ (?: (\r) | ([^\r]) ) \n }x;```
At most one will be true, and both false only if the file is one non-line-terminated stream.


(Then there's the question of Legacy MacOS text files? Is it true they used `\r`  instead of linefeed as their `\n`? Do you find them having migrated un-uncoverted via archives or whatnot ? )

**Comment by petdance** [comment]
Let's remember that this is only in the optimization to say "Do I need to do an actual line scan?"  

Maybe we just drop the `$` from the regex for that optimization and if it gives false positives that's OK.

**Comment by n1vux** [comment]
On Sat, Aug 24, 2019, 11:53 AM Andy Lester <notifications@github.com> wrote:

> Let's remember that this is only in the optimization to say "Do I need to
> do an actual line scan?"
>
> Maybe we just drop the $ from the regex for that optimization and if it
> gives false positives that's OK.
>

Editing the RE is fraught in general, but for the heuristic only,
plausible.

Note that \z is like also going to be a problem for the heuristic in
presense of Windows or network line endings, so need to remove that two
char sequence also.

Pedantic reminder, thanks to syntax, it is possible the $ or \z doesn't
have to be the last character of a valid matchable RE. Unlikely, but
possible.

>

**Comment by petdance** [comment]
I took a nap and I think I have the answer.  If there's `/r` anywhere in the buffer, then we say "yes, we need a line-by-line scan".  No mucking with the regex, no transforming the buffer.

**Comment by n1vux** [comment]
Andy Lester wrote:

> I took a nap and I think I have the answer. If there's /r anywhere in the
> buffer, then we say "yes, we need a line-by-line scan". No mucking with the
> regex, no transforming the buffer.
>
That guarantees correctness easily, but will have same speed loss on
Windows as skipping the heuristic* ‡

*(or even slightly worse that omitting heuristic, since it still does
`sysread` and `index`‡ on the big buffer before bailing)

†(I'm guessing the built-in `index` is the most efficient way in Perl5 to
scan a string for a single character, using the heuristic to prefer
built-ins so looping in C)

‡(except for any files that are POSIX line-endings because some GNUish tool
defies local convention, e.g. CygWin, which makes it worth it for _some_
users).

**Comment by petdance** [comment]
Good point about `index` vs a regex.  Thanks.

**Comment by petdance** [comment]
This has been fixed on `dev` and will be released in either v3.1.1 or v3.2.0, whichever comes next.
