### ISSUE TITLE
The tricky regex we build with `-w` and non-simple patterns causes slowness

### ISSUE THREAD

**Issue by petdance** [beyondgrep/ack3#231]
If we're searching for `foo` with `-w`, we build the regex as `\b(?:foo)\b`.  No problem.

If we're searching for `foo\w+` with a `-w`, we build the regex as `qr/(?i)(?:^|\b|\s)\K(?:foo\w+)(?=\s|\b|$)/i;`  The `$` in the end of that regex means that we can't do a bulk file-scan optimization.

Can we do the bulk file-scan optimization if the `$` is just from our tricky wordifier?

**Comment by petdance** [comment]
See also #181 which seems related, but predates the `$` bug fix.

**Comment by n1vux** [comment]
(a) we could do the bulk scan heuristic w/o the wordifier, so that it errs false-positive (not safe for -v)
   this is consistent: bulk gets the fast RE to reduce the candidate files that get slow scanned.
   This is still better than slow scanning everything, even if a number of files containing "`widow`" are scanned for `-w` `dow` 

(b) we could modify the wordification for bulk (and bulk on windows) to DWIM

**Comment by petdance** [comment]
> do the bulk scan heuristic w/o the wordifier, so that it errs false-positive 

Beautiful.  Thank you.  I'll work on that.

**Comment by petdance** [comment]
This is fixed at e7aa7aa.  It will be released in 3.1.1 or 3.2.0.
