### ISSUE TITLE
Allow -x and --type to WORK together

### ISSUE THREAD

**Issue by devjgm** [beyondgrep/ack3#303]
This feature request is exactly the opposite of https://github.com/beyondgrep/ack3/issues/241. In particular, I'd like to do  `git ls-files | ack -x --perl`, but the `--perl` flag is ignored. Rather than warning about that, can we make it work? Or can we add a flag like `--seriously-dont-ignore-type` to allow us make this work?

/cc @toddr, @pdl

**Comment by n1vux** [comment]
This is an interesting suggestion.

Ack's meta-rules are that the user knows what they're doing, and that  specific inputs are preferred over general (so if you ask for `--perl *.sh` it will happily process the shell files). 

Interpreting the "user knows" to mean "I really want to filter the `-x` input as `--perl`" is plausible. Since `ack  --type` filtering is better than `ls` or `find` filtering, this makes some sense - and while the general suggestion would be using `ack -f` --type=xxx` (or `ack -g`) to generate the original list, sometimes just that isn't an option, e.g. your `git ls-files | ` suggestion .

**Comment by petdance** [comment]
Bill has it right: The intent of `-x` is to be analogous to `xargs`.  If you specify a filename, whether via stdin+`-x` or on the command line, the type will not matter.

So calling `ack foo filename.php --perl` will not filter out the PHP file, because you specified the filename.

What if it was something like:

    git ls-files | ack -x --reduce-by-type --perl | ack -x pattern

There we would have a mode where it takes a list of files from STDIN and then reduces it according to the type of the file.  Then that would be a way to use ack's type detection abilities, what we've been calling file selection, without tying it to the action of searching.

**Comment by devjgm** [comment]
Thank you both for the prompt and thoughtful comments and discussion.

> So calling `ack foo filename.php --perl` will not filter out the PHP file, because you specified the filename.

As a user, the current behavior is surprising to me. I realize that in the example the user specified two seemingly contradictory things: Search in this one `.php` file but filter the files to only perl files. Sure, that seems like a silly thing to ask for, but I agree with the philosophy that the "user knows what they're doing". And therefore, it seems clear to me that all files should be filtered out (i.e., the `--perl` flag should filter out the lone `.php` file argument), because that's what the user asked to it do. 

It's surprising to me that the following two ack invocations produce different output.

```shell
$ ls
a.sh  b.sh  c.md  d.md

$ ack -f --shell *
a.sh
b.sh
c.md
d.md

$ ack -f --shell .
b.sh
a.sh
```

The fact that type filter arguments are ignored when receiving the file list from `ack -x` is even more surprising to me.

Maybe I could phrase my request a slightly different way. I love ack. It's awesome, so naturally I want to use it -- and all of its power -- everywhere I can. However, sometimes I need to offload finding the set of potential files to search to something else, because normally walking the directory structure doesn't produce the right results. In this case, I'd like to select the set of files outside of ack, then tell ack to do all of its normal operation given my custom list of files.

The actual example I'm talking about here is I want the input to be `git ls-files`. The suggestion about using a `ack --reduce-by-type` flag as a step in a pipeline doesn't really help because then I have to pre-process the command-line flags passed to _my_ `git-ack` script so that I can extract ack's type filtering flags and then optionally insert this step. That path is fraught with peril.

The ideal behavior I want is `git ls-files | ack -x "$@"`. And I think getting that behavior today without help from ack is very difficult.

**Comment by devjgm** [comment]
One more example that suggests that users may well _expect_ ack's type filters to work even when given lists of files is to compare this behavior to find(1).

```shell
$ ls
a.sh  b.sh  c.md  d.md

$ find * -name '*.sh'
a.sh
b.sh

$ ack -f --shell *
a.sh
b.sh
c.md
d.md
```
As a user, it seems like I'm asking both `find` and `ack` the same question: "What are all the shell scripts in this directory?" `find` answered the question, and I think everyone would expect and understand why `find` did what it did.

Given essentially the same input, `ack` did not answer the question (correctly). And I think at least some users (myself included) will be surprised by ack's output.

**Comment by petdance** [comment]
Thanks for your comments.

It might be that I need to be clearer in the docs about usage of the `--type` options.  The `--type` options are only for when ack is selecting files for you.  Specifying filenames on the command line, and that includes for example `ack foo *`, means that ack trusts that you meant to search those files.

ack doesn't want you to specify filenames if you don't have to.  If you want to find shell in the current directory, then do `ack -f --shell -n`.

This isn't going to change in ack 3, because it would be a big change in behavior and would require a major version change, to ack 4.

I'm interested in how we might add a filtering by type feature to ack 3.  That will need to be in a new, different issue.
