### ISSUE TITLE
colored input

### ISSUE THREAD

**Issue by Emilv2** [beyondgrep/ack3#318]
ack doesn't seem to work very well with colored input, is this simply not supported or could these be considered bugs?

```
printf "'\033[0;31mNow there is color, now there is not\n" | ack --color color
```
The red color doesn't go on after `color`. while in the original string it does not.

```
printf "'\033[0;31mThe \033[0;32munderline \033[031;mshould be there, but it's over here.\n" | ack --underline there
```
The underline should be under `there` but due to the color codes it ends under `here`.

**Comment by petdance** [comment]
Yes, ack doesn't work with colored input the way you are expecting.

In your first example, ack turns off the coloring because it's done highlighting the word "color".  It doesn't know that the original string had color codes in it.

In the second example, ack doesn't know that some of the characters don't print, so the calculations to figure where the underline should go get messed up.

This is not a bug.

**Comment by Emilv2** [comment]
Yes I see what is happening, my question was more like why is this not done? Compability with grep?

**Comment by petdance** [comment]
It's never been something I've ever thought about it before.  I've never heard of anyone wanting to search text files that have ANSI color codes in them and have those color codes respected.

**Comment by hftf** [comment]
I don't have text files containing color codes, but in maybe a handful of complex use cases per year, I've wanted to search the output of a command or script and preserve meaningful color codes (for lightweight syntax highlighting – including [meaningful](https://github.com/jgm/pandoc/pull/2270#issuecomment-282560598) bold and underline elements contained in most of my documents – but more often just the result of another `ack` or `grep` search). That would be nice to see when searching.

**Comment by n1vux** [comment]
> wanting to search text files that have ANSI color codes in them

as long as we position Ack as a _source-code_ search-tool and _not_ a general-purpose/natural-language-text search-tool, ANSI color-codes are reasonably considered out-of-scope. 

Yes, we all _do_ make use of Ack to filter our program input- and output-data _as well_ as program code (i even use it for natural-language corpus search) but that is _off-label_ use; we _should_ be pleasantly surprised how _well_ it works in _off-label_ usage on data.

(This explicates one of the barriers to making Ack (or an Ack-fork) into a proper natural-language tool -- it would be _expected_ that we could parse non-NL tokens out of the stream (ANSI-color and Unicode and HTML/XML markup etc). And then would need flags to indicate which filtering to use on STDIN. Since we do NOT parse the HTML even when `--html` is in effect, this would be a major scope change. If one wants XML/HTML parsing in a Grep, see [xml_grep](https://metacpan.org/pod/distribution/XML-Twig/tools/xml_grep/xml_grep) . Suddenly i grok Andy's reticence to add NL-leaning features.)
