### ISSUE TITLE
Browsing at root of system resources not allowed

### ISSUE THREAD

**Issue by Ricky-Tigg** [beyondgrep/ack3#355]
Browsing at root of system resources not allowed | [ack_dump.txt](https://github.com/beyondgrep/ack3/files/8214618/ack_dump.txt)

```shell
$ ack --version | head -2
ack v3.5.0 (standard build)
Running under Perl v5.34.0 at /usr/bin/perl
$ cd /; sudo ack '<pattern>'
ack: proc/sys/abi/vsyscall32: Cannot allocate memory
[...]
ack: proc/sysrq-trigger: Input/output error
ack: proc/1/task/1/mem: Input/output error
ack: proc/1/task/1/clear_refs: Invalid argument
[...]
```

**Comment by petdance** [comment]
That seems about right. The /proc directory is going to have all sorts of stuff in it that you probably shouldn't be looking through.

What do you expect to happen when you try looking in `/proc/sysrq-trigger`?  grep gives the same Input/output error.

**Comment by Ricky-Tigg** [comment]
I used to know there was protected files. I bothered you unnecessarily.. 

_Message displayed at boot_:

![Exhibited_Openssl_URL_during_boot](https://user-images.githubusercontent.com/26058215/157657298-ec244d21-794a-4ebf-a5ba-5d330eb44e98.png)

I had attempted to figure out its origin. I would not know where to search from and what file type to filter; that motivated me to search globally.. Since your comment i understand the need to exclude folders known to hold protected content – with `--ignore-dir` for instance.

**Comment by petdance** [comment]
Not a problem at all. I do suggest that you use grep and not ack for this, because the files you are looking might be binary, and ack ignores binary files.

You could do something like this:

    find / -type f | grep -v ^/proc/ | xargs grep -i -l tiano

Find all the files in the filesystem, and then exclude all those that are in the `/proc/` path, and then search each of those for the string `tiano`, case-insensitively, but only show the filenames of the matching files, because you don't want to see the text that matches at this point.

There is a way to use options with `find` to exclude the `/proc` directory directly, but I think just `grep -v` on the list of files will do fine.
