### ISSUE TITLE
bad interpreter: /usr/bin/perl5.30: no such file or directory

### ISSUE THREAD

**Issue by XSchelin** [beyondgrep/ack3#384]
I've just started getting an issue when I attempt to run `ack`:

```
zsh: /opt/homebrew/bin/ack: bad interpreter: /usr/bin/perl5.30: no such file or directory
```

I'm running ack 3.7.0. For Perl, what I do have is `/usr/bin/perl5.34`, but no 5.30.

How do I go about fixing this?

**Comment by n1vux** [comment]
👍

Apparently you'd upgraded Perl  since last use of Ack (which is a good thing to do) 
(or copied the Ack script to a different system with a newer Perl).

Reinstalling is remarkably effective.

Alternative solutions include

- editing the script first line to change the 30 to  34, to find the Perl you now have.
- linking whichever Perl was last installed by Homebrew (or whatever) as /usr/bin/perl and deleting the numbers from the #! in scripts so they don't need updating whenever Perl is updated
- replacing the #! /usr/bin/perl5.xx with #! /usr/bin/env perl , which will pick whatever perl is on your PATH 

all of which work for any Perl scripts you might have that don't have installers as well as for Ack and others that do.
