### ISSUE TITLE
Consistent punctuation in man page

### ISSUE THREAD

**Issue by 7373Lacym** [beyondgrep/ack3#84]
After a few skims of the man pages it looks like we use a period followed by two spaces in some places and a period followed by one space in others.  This is nitpicky but is an easy fix and a good first pr.  Let me know what you all think.

**Comment by petdance** [comment]
I'm all for consistency, and I don't see it as nitpicky, and I prefer to use two spaces after a period when we're dealing with text that is usually seen in a fixed-width font.  That said, I'd prefer to clean up those differences as part of other changes, rather than on their own.

Are there textual improvements that you see that we can make?
